#distributed_training:
#  ddp_backend: legacy_ddp
#  distributed_world_size: 2

common:
  log_interval: 1 # ####################
  fp16: true
  log_format: json
  memory_efficient_fp16: false
  on_cpu_convert_precision: false

checkpoint:
  save_interval_updates: 1000 
  keep_interval_updates: 3
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer
  save_interval: 500 # Cada cuantas epocas salvar

task:
  max_sample_size: 560000 #25 seconds (400000/16000)
  min_sample_size: 16000 #1 seconds
  _name: audio_finetuning 
  data: .../bribri/
  normalize: true
  labels: ltr

dataset:
  validate_interval_updates: 1000 
  train_subset: train_bribri # ####################
  valid_subset: dev_bribri # ####################
  max_tokens: 560000 
  num_workers: 6
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 1000 

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 10000 
  lr: [0.0001] 
  sentence_avg: true
  update_freq: [10]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  freeze_finetune_updates: 2000 
  _name: wav2vec_ctc
  w2v_path: .../xlsr2_300m.pt
  apply_mask: true
  mask_prob: 0.25 
  mask_channel_prob: 0.5 
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  checkpoint_activations: false
